INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (1, '/assets/images/tribune-slider.jpg', 'Microphone.', null);
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (2, '/assets/images/balados-slider.jpg', 'Parlement d''Ottawa.', null);
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (3, '/assets/images/lagenda-slider.jpg', 'Bureau.', null);
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (4, '/assets/images/lagenda-2-slider.jpg', 'Parlement de Québec.', null);
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (5, '/assets/images/placeholder.jpg', 'Placeholder image.', null);
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (6, '/assets/images/photoJonathan.jpg', 'Photo Jonathan Carreiro-Benoit.', null);
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (7, '/assets/images/photoJeremie.jpg', 'Photo Jérémie Juneau.', null);
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (8, '/assets/images/photoNicolas.jpg', 'Photo Nicolas Signori.', null);
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (9, '/assets/images/photoGabrielle.jpg', 'Photo Gabrielle.', null);
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (10, '/assets/images/photoAdam.jpg', 'Photo Adam Fontaine-Métivier.', null);
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (11, '/assets/images/photoAntoine.jpg', 'Photo Antoine Poulin.', null);
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (12, '/assets/images/photoJordan.jpg', 'Photo Jordan Larochelle.', null);
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (13, '/assets/images/photoSamuel.jpg', 'Photo Samuel Lamarche.', null);
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (14, '/assets/images/photoMarieLaurence.jpg', 'Photo Marie-Laurence Desgagné.', null);
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (15, '/assets/images/photoLiam.jpg', 'Photo Liam Buell.', null);
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (16, '/assets/images/balado1.jpg', null, 'Radio-canada');
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (17, '/assets/images/balado3.jpg', 'Masque rue.', null);
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (18, '/assets/images/article7.jpg', 'Étagères vides.', 'RADIO-CANADA / THOMAS GERBET');
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (19, '/assets/images/article8.jpg', 'Conférence de presse Québec.', 'RADIO-CANADA / SYLVAIN ROY ROUSSEL');
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (20, '/assets/images/article9.jpg', 'Jean Lessage après sa victoire en 1960.', 'ARCHIVES LA PRESSE/RÉAL SAINT-JEAN');
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (21, '/assets/images/article10.jpg', 'G20.', 'Jesco Denzel/Associated press');
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (22, '/assets/images/article11.jpg', 'Sylvain Gaudreault.', 'La Presse canadienne / Jacques Boissinot');
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (23, '/assets/images/article12.jpg', 'Le Panier Bleu.', 'Capture d''écran - Gouvernement du Québec');
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (24, '/assets/images/article13.jpg', 'Concertation avec l''opposition.', 'Compte Twitter de François Legault');
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (25, '/assets/images/article14.jpg', 'Conférence de presse de Justin Trudeau.', 'La presse canadienne/Fred Chartrand');
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (26, '/assets/images/article15.jpg', 'Robert Bourassa et Jacques Parizeau.', 'La Presse canadienne / Paul Chiasson');
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (27, '/assets/images/article16.jpg', 'Sables pitumineux.', 'Dan Barnes Photography/iStock');
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (28, '/assets/images/article17.jpg', 'Commerce fermé.', 'RADIO-CANADA / IVANOH DEMERS');
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (29, '/assets/images/article18.jpg', 'Indépendance de la Catalogne.', 'Tony Cartalucci/Global Research');
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (30, '/assets/images/article6.jpg', 'Justin Trudeau et François Legault', 'La Presse canadienne');
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (31, '/assets/images/article1.jpg', 'Samuel Lamarche et Jonathan Carreiro-Benoit.', null);
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (32, '/assets/images/article2.jpg', 'PHOTO JUSTIN TANG, LA PRESSE CANADIENNE', 'PHOTO JUSTIN TANG, LA PRESSE CANADIENNE');
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (33, '/assets/images/article5.jpg', 'PHOTO : GETTY IMAGES / RAFAEL YAGHOBZADEH', 'PHOTO : GETTY IMAGES / RAFAEL YAGHOBZADEH');
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (34, '/assets/images/article4.jpg', 'PHOTO AGENCE QMI, MAXIME DELAND', 'PHOTO AGENCE QMI, MAXIME DELAND');
INSERT INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (35, '/assets/images/article19.jpg', 'Crédit photo : Evan Vucci/AP', 'Crédit photo : Evan Vucci/AP');