SET FOREIGN_KEY_CHECKS=0;
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (1, '/assets/images/tribune-slider.jpg', 'Microphone.', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (2, '/assets/images/balados-slider.jpg', 'Parlement d''Ottawa.', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (3, '/assets/images/lagenda-slider.jpg', 'Bureau.', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (4, '/assets/images/lagenda-2-slider.jpg', 'Parlement de Québec.', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (5, '/assets/images/placeholder.jpg', 'Placeholder image.', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (6, '/assets/images/photoJonathan.jpg', 'Photo Jonathan Carreiro-Benoit.', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (7, '/assets/images/photoJeremie.jpg', 'Photo Jérémie Juneau.', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (8, '/assets/images/photoNicolas.jpg', 'Photo Nicolas Signori.', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (9, '/assets/images/photoGabrielle.jpg', 'Photo Gabrielle.', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (10, '/assets/images/photoAdam.jpg', 'Photo Adam Fontaine-Métivier.', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (11, '/assets/images/photoAntoine.jpg', 'Photo Antoine Poulin.', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (12, '/assets/images/photoJordan.jpg', 'Photo Jordan Larochelle.', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (13, '/assets/images/photoSamuel.jpg', 'Photo Samuel Lamarche.', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (14, '/assets/images/photoMarieLaurence.jpg', 'Photo Marie-Laurence Desgagné.', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (15, '/assets/images/photoLiam.jpg', 'Photo Liam Buell.', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (16, '/assets/images/balado1.jpg', null, 'Radio-canada');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (17, '/assets/images/balado3.jpg', 'Masque rue.', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (18, '/assets/images/article7.jpg', 'Étagères vides.', 'RADIO-CANADA / THOMAS GERBET');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (19, '/assets/images/article8.jpg', 'Conférence de presse Québec.', 'RADIO-CANADA / SYLVAIN ROY ROUSSEL');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (20, '/assets/images/article9.jpg', 'Jean Lessage après sa victoire en 1960.', 'ARCHIVES LA PRESSE/RÉAL SAINT-JEAN');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (21, '/assets/images/article10.jpg', 'G20.', 'Jesco Denzel/Associated press');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (22, '/assets/images/article11.jpg', 'Sylvain Gaudreault.', 'La Presse canadienne / Jacques Boissinot');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (23, '/assets/images/article12.jpg', 'Le Panier Bleu.', 'Capture d''écran - Gouvernement du Québec');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (24, '/assets/images/article13.jpg', 'Concertation avec l''opposition.', 'Compte Twitter de François Legault');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (25, '/assets/images/article14.jpg', 'Conférence de presse de Justin Trudeau.', 'La presse canadienne/Fred Chartrand');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (26, '/assets/images/article15.jpg', 'Robert Bourassa et Jacques Parizeau.', 'La Presse canadienne / Paul Chiasson');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (27, '/assets/images/article16.jpg', 'Sables pitumineux.', 'Dan Barnes Photography/iStock');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (28, '/assets/images/article17.jpg', 'Commerce fermé.', 'RADIO-CANADA / IVANOH DEMERS');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (29, '/assets/images/article18.jpg', 'Indépendance de la Catalogne.', 'Tony Cartalucci/Global Research');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (30, '/assets/images/article6.jpg', 'Justin Trudeau et François Legault', 'La Presse canadienne');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (31, '/assets/images/article1.jpg', 'Samuel Lamarche et Jonathan Carreiro-Benoit.', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (32, '/assets/images/article2.jpg', 'PHOTO JUSTIN TANG, LA PRESSE CANADIENNE', 'PHOTO JUSTIN TANG, LA PRESSE CANADIENNE');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (33, '/assets/images/article5.jpg', 'PHOTO : GETTY IMAGES / RAFAEL YAGHOBZADEH', 'PHOTO : GETTY IMAGES / RAFAEL YAGHOBZADEH');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (34, '/assets/images/article4.jpg', 'PHOTO AGENCE QMI, MAXIME DELAND', 'PHOTO AGENCE QMI, MAXIME DELAND');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (35, '/assets/images/article19.jpg', 'Crédit photo : Evan Vucci/AP', 'Crédit photo : Evan Vucci/AP');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (36, '/assets/images/93189214_10158819334804523_848938391004250112_n.jpg', null, null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (37, '/assets/logo/logoTextWhite.jpg', 'Logo L''Agenda', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (38, '/assets/images/photoJeremy.jpg', 'Photo Jeremy', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (39, '/assets/images/photoDereck1.jpg', 'Photo Dereck', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (40, '/assets/images/100549396_1479782558870833_7118105413408522240_n.png', 'Photo Sylvain Gaudreault.', 'Page Facebook Sylvain Gaudreault.');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (41, '/assets/images/100583617_384612222460903_9070458767186853888_n.png', 'Photo Dominique Anglade.', 'https://plq.org/fr/');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (42, '/assets/images/100788897_2605081263154043_5854462933265809408_n.png', 'Photo Sylvain Gaudreault.', 'Page Facebook Sylvain Gaudreault.');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (43, '/assets/images/photoAnglade.jpg', 'Photo Dominique Anglade.', 'https://plq.org/fr/');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (44, '/assets/images/extra/Photo-Aime-auteur.png', 'Photo Aimé auteur', 'Aimé Pingi');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (45, '/assets/images/extra/Photomaniffloyd.png', 'Photo manif Floyd', 'Aimé Pingi');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (46, '/assets/images/extra/Simon-Provost.jpg', 'Photo profil Simon', 'Simon Provost');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (47, '/assets/images/extra/Photo-Natasha.png', 'Photo profil Natasha', 'Natasha Tremblay');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (48, '/assets/images/extra/Photo-PSPP.jpg', 'Photo Paul', 'PSPP');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (49, '/assets/images/extra/Photo-Profil-PSPP.jpg', 'Photo Profil Paul', 'PSPP');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (50, '/assets/images/extra/Photo-Guy-Nantel-1.jpg', 'Photo Article Guy Nantel', 'Guy Nantel');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (51, '/assets/images/extra/Photo-Alexis-Bedard.jpg', 'Photo Profil Alexis', 'Alexis');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (52, '/assets/images/extra/Image-Dieudonné.jpg', 'Photo auteur Dieudonné', 'Dieudonné');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (53, '/assets/images/extra/Photo-Laurent-Vézina.jpg', 'Photo auteur Laurent Vézina', 'Laurent Vézina');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (54, '/assets/images/extra/Laurent-Vézina-Article.jpg', 'Photo Article Laurent Vézina', 'Laurent Vézina');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (55, '/assets/images/extra/Image-pod-course-à-la-chefferie.jpg', 'Image-pod-course-chefferie', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (56, '/assets/images/extra/Image-pod-special-covid.jpg', 'Image-pod-special-covid', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (57, '/assets/images/extra/Image-pod-Jérémie-Juneau-autonomiste-et-social-démocrate.jpg', 'Image-pod-Juneau', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (58, '/assets/images/extra/image-pod-quelles-reformes-apres-la-crise.jpg', 'Image-pod-Réforme après la crise', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (59, '/assets/images/extra/Image-pod-les-gouvernements-et-le-monde.jpg', 'Image-pod-Les gouvernement et le monde', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (60, '/assets/images/extra/Image-pod-la-bureaucratie-et-le-déconfinement.jpg', 'Image-pod-La bureaucratie et le déconfinement', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (61, '/assets/images/extra/Image-pod-le-sport-et-la-covid.jpg', 'Image-pod-le sport et la covid', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (62, '/assets/images/extra/Image-pod-le-mental-et-le-social.jpg', 'Image-pod-Le mental et le social', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (63, '/assets/images/extra/Image-pod-les-patriotes-et-l''histoire.jpg', 'Image-pod-Les patriotes et l''histoire', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (64, '/assets/images/extra/Image-pod-les-defis-de-dominique-anglade.jpg', 'Image-Pod-Anglade', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (65, '/assets/images/extra/Image-pod-les-conservateurs-et-le-Québec.jpg', 'Image-pod-Natasha', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (66, '/assets/images/extra/Image-pod-le-plan-gaudreault-pour-l''indépendance.jpg', 'Image-Pod-Plan Gaudreault', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (67, '/assets/images/extra/Image-pod-contester-le-regime-fédéral.jpg', 'Image-Pod-Contester le régime fédéral', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (68, '/assets/images/extra/Image-pod-personne-ne-gagne-ses-négociations-dans-le-corridor.jpg', 'Image-Pod Personne ne gagne ses négocations dans le corridor', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (69, '/assets/images/extra/Photo-Auteur-Bastien.jpg', 'Photo Auteur Bastien', 'Page facebook de Bastien');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (70, '/assets/images/extra/Image-Robert-Bob-Sirois.jpg', 'Photo Podcast Bob Sirois', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (71, '/assets/images/extra/La CAQ et les autres.jpg', 'Photo Podcast CAQ', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (72, '/assets/images/extra/Image-Carl.jpg', 'Photo Carl Vaillancourt', 'Carl');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (73, '/assets/images/extra/Le PLC et Trudeau.jpg', 'Photo podcast trudeau', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (74, '/assets/images/extra/Prisonniers des Îles.jpg', 'Photo podcast Joel ', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (75, '/assets/images/extra/La reprise du sport.jpg', 'Photo pod Goutts ', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (76, '/assets/images/extra/116337916_3086983291412481_1487644338561698305_n.png', null, null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (77, '/assets/images/extra/Aller_plus_loin_que_la_partisanerie.jpg', null, null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (78, '/assets/images/extra/116797787_405703180391945_1492608175940356874_n.jpg', null, null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (79, '/assets/images/extra/117392871_688051771923707_4454452187640618313_n.jpg', null, null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (80, '/assets/images/extra/117690813_754412475358074_1589742063074146003_n.jpg', null, null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (81, '/assets/images/extra/Félix_Lachance.jpg', null, null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (82, '/assets/images/extra/Un retour aux sources.jpg', 'Anglade', 'Page facebook anglade');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (83, '/assets/images/extra/Leçon d''histoire.jpg', 'Paul Crete', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (84, '/assets/images/extra/Coup d''oeil chez les solidaires.jpg', 'Solidaires', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (85, '/assets/images/extra/Le dernier sprint.jpg', 'Carl et vincent', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (86, '/assets/images/extra/Le conservatisme et le nationalisme au Québec.jpg', 'EA-Beauregard ', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (87, '/assets/images/extra/Charles-Hubert crop.png', 'Charles-Hubert', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (88, '/assets/images/extra/Courrier du lecteur.jpg', 'Courrier du lecteur', 'Photo by Fire Horse Leo on Foter.com / CC BY-SA');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (89, '/assets/images/extra/La nouvelle voie des jeunes.jpg', 'Keven Brasseur', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (90, '/assets/images/extra/Faire la politique autrement.jpg', 'Ruba Gazal ', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (91, '/assets/images/extra/Photo Justin Lachapelle.jpg', 'Justin ', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (92, '/assets/images/extra/De la parole aux actes.jpg', 'Sylvain ', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (93, '/assets/images/extra/Photo Justin Dubé.jpg', 'Justin Dubé', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (94, '/assets/images/extra/Cette langue qui dérange.jpg', 'Pod Français', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (95, '/assets/images/extra/Photo Justin Dubé carré.png', 'Justin Dubé Carré', null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (96, '/assets/images/extra/Ass Nat.png', 'Photo Ass Nat', 'Photo by JefferyTurner on Foter.com / CC BY');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (97, '/assets/images/extra/Le mouton noir du Québec.jpg', null, null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (98, '/assets/images/extra/129724232_711047876501304_5433344699516902206_n.png', null, 'Photo by marthelelièvre on Foter.com / CC BY-ND');
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (99, '/assets/images/extra/Retour sur 2020.jpg', null, null);
replace INTO lagenda_api.Images (Id, Url, Alt, Credits) VALUES (100, '/assets/images/extra/Cap sur les élections.jpg', null, null);